apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-zipw
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jsvh-tenant/rhtap-demo-app/hacbs-test-project-zipw@sha256:8795fbc25c9a4e1ebc87c57d03eed8de92c0a893bac1ed9fb0efb4b1e7f543ee
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
